### ISSUE TITLE
Ekstra Konaklama Bilgileri

### ISSUE THREAD

**Issue by coderserdar** [alpaylan/afetbilgi.com#1]
https://www.otelz.com/gecmisolsunturkiyem?fbclid=PAAaaBLy77gaam2hBFeWnuR8GOjOI7HOStgXmb7Hx-RsAFf9YJGcnYUr9tVCE

[Otelz.Com](https://www.otelz.com/) yukarıdaki linki yayınlamış. Twitter üzerinden gördüm. Bu bilgiler de çekilerek konaklama kısmı daha zenginleşir diye düşünüyorum.
Sitede şehir şehir ücretsiz konaklama hizmeti veren otellerin iletişim bilgileri ve ne kadar oda ayrıldığının bilgileri mevcut

**Comment by oznakn** [comment]
Çok teşekkürler, inceliyoruz.
