### ISSUE TITLE
Afad Kayıt Buton

### ISSUE THREAD

**Issue by Arkadhan** [alpaylan/afetbilgi.com#111]
Afada kayıt olmak için bir buton ve yönlendirme eklenebilir.
Aynı şekilde devletin verdiği yardımdan faydalanmaları için SGK ya yönlendirien bir buton eklenebilir. 
mervebasakın önerisidir.

**Comment by yigitv4rli** [comment]
Alakali bilgileri bana iletebilirseniz nasil bir sey yapabilecegimize bakalim. Twitterdan yigit_v4rli veya yigit.v4rli@gmail.com adresinden bana ulasabilirsiniz
