### ISSUE TITLE
Kızılay Kan Bağışı Butonunun Çalışma Mantığının Değiştirilmesi

### ISSUE THREAD

**Issue by alpaylan** [alpaylan/afetbilgi.com#122]
Şu anda direkt redirect atıyor. Bu kafa karıştırabilir. O sayfaya girsin ordan link verelim. Navige etmek istemeyenler yanlışlıkla etmesinler.

**Comment by ilkerkosaroglu** [comment]
Yeni sayfa yaratmak yerine link olduğunu belli etmesi için underline ekledim, pr'ı açık. Gelecekteki değişikliklere uygun olması adına başka bir şey yapalım dersen pr'ı kaldıralım
