### ISSUE TITLE
Anasayfada sehir secimi

### ISSUE THREAD

**Issue by ozansz** [alpaylan/afetbilgi.com#142]
Su anda sehir secimi menu item sectikten sonra bazi itemlar icinde geliyor. Istedigimiz bunun yaninda header'da bir sehir dropdown'i olmasi ve dogrudan menu itemlari icindeki contentleri sehire gore filtreleyerek sitede sadece spesifik bir sehir icin bilgi aranabilmesi.

**Comment by Kaanayden** [comment]
Kimse görevi almadıysa yapabilirim
