### ISSUE TITLE
Pdf  formatında "adres" stununda "tarih" yayınlanması..

### ISSUE THREAD

**Issue by emrahburak** [alpaylan/afetbilgi.com#149]
Selamlar.
Pdf olarak indir dediğimizde 'adres' stunu altında 'dogrulanma tarihleri' geliyor..

**Comment by sadikkuzu** [comment]
Düzelmiş gibi görünüyor: https://cdn.afetbilgi.com/md-pdf/tr/afetbilgi.pdf

**Comment by sadikkuzu** [comment]
#150

**Comment by ozansz** [comment]
Fixed by https://github.com/alpaylan/afetbilgi.com/pull/150
