### ISSUE TITLE
bagis.ahbap.eft

### ISSUE THREAD

**Issue by bali-ibrahim** [alpaylan/afetbilgi.com#15]
Ahbap için olan eft bağış bilgisinde:

hesap adı
ya da
alıcı adı
olarak
AHBAP DERNEĞİ
eklenebilir. Zira eft yapılırken eğer başka bankaysa bu bilgi gerekiyor. Ek olarak kaynak da olsa iyi olur:
https://ahbap.org/bagisciol

**Comment by alpaylan** [comment]
Hocam Merhaba, bağış bilgilerini kaldırmak durumunda kaldık sitede.
