### ISSUE TITLE
Mony donations altında sayfaların isimleri Türkçe yazıyo. Çeviriyle uğraşmayıp direkt kurum ismini bırakalım

### ISSUE THREAD

**Issue by alpaylan** [alpaylan/afetbilgi.com#162]

**Comment by sadikkuzu** [comment]
[donation_links.json](https://github.com/alpaylan/afetbilgi.com/blob/main/data/datasets/donation_links.json) dosyasında düzenleme yapmak yeterli mi?

**Comment by yigitv4rli** [comment]
Evet hocam yeterliydi, yapi olarak name_tr, name_en .. kullaniyoruz eger diger dilleri de ekliyorsak. Ama ben dedigimiz fix'i gectim. Tesekkurler :) @sadikkuzu

**Comment by sadikkuzu** [comment]
Süpersiniz hocam ellerinize sağlık 👏🏼 ✨ 👍🏼  @yigitv4rli
