### ISSUE TITLE
Direkt Linklerin Yeni Sekmede Açılması

### ISSUE THREAD

**Issue by coderserdar** [alpaylan/afetbilgi.com#187]
Ana sayfada yer alan
Mobil Tuvaletler ve Kızılay Kan Bağış Noktaları linklerine tıklandığı zaman aynı sayfada yönlendirme yapması yerine
Yeni bir sekmede açılması sağlanırsa
Kullanıcılar site içerisinde hem yeni sekmede işini hallederken hem de diğer sayfalara göz atabilir.
Daha hızlı işlem gerçekleştirilebilmesi mümkün olur diye düşünüyorum

**Comment by Ayb3rk** [comment]
https://github.com/alpaylan/afetbilgi.com/pull/189

**Comment by coderserdar** [comment]
Özellik eklenmiş, elinize sağlık
İyi çalışmalar
