### ISSUE TITLE
Toplanma Bilgileri Hakkında

### ISSUE THREAD

**Issue by coderserdar** [alpaylan/afetbilgi.com#2]
İncelediğim kadarıyla toplanma bilgileri ile ilgili olarak güzel bir çalışma yapılmış. Ellerinize sağlık.
Ancak siteye giren insanlar için toplanma yerlerinin adlarının yanına direkt olarak google maps konumu link olarak eklenirse, hızlıca haritalarda aratmadan tıklayarak bu adreslere daha hızlı bir şekilde yönlendirme yapılması sağlanabilir

**Comment by oznakn** [comment]
Merhaba,

Konu üstünde çalışıyoruz şu an, çok teşekkürler.

**Comment by coderserdar** [comment]
Rica ederim hocam. Typescript ve python vb. dillerde çok tecrübem olmadığı için ben de elimden geldiğince hem size hem de depremyardim.com repolarına katkıda bulunmaya çalışıyorum.
