### ISSUE TITLE
Misafir Etme Sayfası

### ISSUE THREAD

**Issue by coderserdar** [alpaylan/afetbilgi.com#27]
Ufak bir kayıt ekranı yapılarak, imkanı olan vatandaşlarımızın evlerinde kaç depremzedeyi misafir edebileceğine dair bilgiler girilirse;
Siteye giren vatandaşlarımız, adres bilgisine bakarak kendilerine en yakın yardımsever vatandaşımıza gidip kısa bir süre de olsa konaklama, yemek vb. ihtiyaçlarını giderebilir diye düşünüyorum.
Veri giriş ekranında
Ad Soyad (Zorunlu Değil)
Adres (Zorunlu)
Harita Bilgisi (Zorunlu Değil)
Kaç Kişi Misafir Edebilir (Zorunlu)
gibi bilgiler girilerek bir havuz oluşturulabilir

**Comment by coderserdar** [comment]
Yasal mevzulardan dolayı bu konu olmuyormuş anladığım kadarıyla
HepsiEmlak https://www.hepsiemlak.com/emlak-yasam/genel/dostluk-catisi?utm_source=sm&utm_medium=post-ads&utm_campaign=socialmedia böyle bir link paylaşmış
Bunu sayfanın içerisinde bir butonla vb. ele alırsak daha çok kişinin görüp kullanmasını sağlayabiliriz

**Comment by alpaylan** [comment]
Bu tarz dostluk çatısı gibi sistemleri ekledik barınma sayfasının altına. Biz mümkün olduğunca interaktif datalardan kaçmaya çalıştığımız için siteye direkt eklemiyoruz.

**Comment by coderserdar** [comment]
Elinize sağlık. İyi çalışmalar
