### ISSUE TITLE
Grid veya HTML Table Yapısı

### ISSUE THREAD

**Issue by coderserdar** [alpaylan/afetbilgi.com#31]
![Screenshot_1](https://user-images.githubusercontent.com/11051271/217541177-8ae63a26-b530-4e50-bcd9-c96a9ee4d001.png)
Bu sayfadaki gibi konaklama vb. bilgilerini html table veya grid içerisine alabilirsek bence daha düzgün bir görünüme sahip oluruz ve kaplayacağı yer azalacağı için bir sayfada scroll etmeden daha fazla kayıt görüntülenebilir diye düşünüyorum.
Ben de koda müdahil olmak isterim ama bir yerini bozarım dünkü gibi vercel tarafında validate edemez diye de çekiniyorum.
Ancak buraya comment olarak yöntem için örnek bir yapı verebilirseniz bu ve bunun gibi sayfalarda elimden geldiğince hızlı bir şekilde çıkarmaya çalışırım

**Comment by alpaylan** [comment]
Hocam mobilde çok kötü gözükmez mi bu sizce de?

**Comment by coderserdar** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/11051271/217572355-aadad32e-3c30-4d9f-bb62-31653cfe390f.png)
3 kolonlu kısa bir tablo düşünün hocam
ilkinde kurumun adı
ikincisinde url adresi
üçüncüsünde de harita bağlantısı olacak
bence ufak telefonlar için bile takip etmesi kolay bir yapı olur.
Gündoğdu Koleji | Link | Map gibi düşünebilirsiniz. Aradaki metinlerin hiçbirine gerek kalmayacakmış gibi düşünün

**Comment by coderserdar** [comment]
![Screenshot_2023-02-08-21-18-57-26.jpg](https://user-images.githubusercontent.com/11051271/217617664-d766839f-ed63-4290-a98a-a694f1fcf468.jpg)

Elinize sağlık hocam. Fotoğraf telefondan çekilen bir fotoğraf gayet görünür ve düzgün bir şekilde.
