### ISSUE TITLE
maps.afetbilgi.com

### ISSUE THREAD

**Issue by alpaylan** [alpaylan/afetbilgi.com#52]
Ana siteyi yormadan, yine lightweight olacak şekilde afetbilgi.com daki tüm maps.google linklerini bir haritada kategorize bir şekilde toplayan, statik bir map sayfası yapılacak.

Gerekli sub-task'lar aşağıdaki gibi.
- Veri setindeki maps.google linklerinin koordinata çevrilmesi.
- Veri setinden her bir lokasyon için isim-koordinat-kategori şeklinde ayrıldığı yeni bir veri setinin sentezlenmesi.
- Sentezlenen yeni veri setinin lightweight static bir map appi olarak maps.afetbilgi.com a deploylanması
- Bu sürecin otomatizasyonu.

İlgilenecekler arasında @RKursatV ve @ufukygmr var, başka ilgilenmek isteyenlere de açığız.

**Comment by oznakn** [comment]
<img width="973" alt="Screenshot 2023-02-10 at 02 56 11" src="https://user-images.githubusercontent.com/17930378/217965677-1b2e1f67-3045-47d7-9247-9499487155bf.png">

mvp
