### ISSUE TITLE
pdf.afetbilgi.com

### ISSUE THREAD

**Issue by ozansz** [alpaylan/afetbilgi.com#55]
Tum site iceriginin generate edilmis PDF hali icin subdomain. Direkt S3'te ilgili objecte alias olabilir.

Ilgilenen: @ozansz

**Comment by RKursatV** [comment]
@ufukygmr ile epey ilerlettik, gun icinde tamamlayacagiz. S3 entegrasyonu icin uzerine bir tur konusmamiz gerekiyor onun disinda guzel generic bir yapi uzerinden gidiyoruz.

**Comment by RKursatV** [comment]
#53 closes this.
