### ISSUE TITLE
Genel Konaklama Bilgileri 

### ISSUE THREAD

**Issue by coderserdar** [alpaylan/afetbilgi.com#67]
![Screenshot_4](https://user-images.githubusercontent.com/11051271/217818634-22133631-b3a9-4508-8d6b-2d011f5e69ec.png)

Bu bilgilerin illerdeki konaklamalara gidildiği zaman da açılmamış bir popup içerisinde her ilde gösterilmesi ve siteye giren ziyaretçiler
İlleri sorguladığı zaman çıkan sayfada isterse o popup bloğunu açarak bu linkleri de görebilmesi
Bu bilgilerin daha çok kişiye ulaşması için daha faydalı olur diye düşünüyorum.

**Comment by yigitv4rli** [comment]
Ilk girilen yer gecici barinma yerleri olacagi icin boyle daha fazla dikkat cektigini dusunuyorum. Diger tarafta birden fazla gozukunce altta popup da olsa gozden kacacaktir.
