### ISSUE TITLE
DepremYardım ve Deprem.io linklerinin eklenmesi

### ISSUE THREAD

**Issue by t3nGri** [alpaylan/afetbilgi.com#69]
Önemli web siteleri bölümünüze aktif olarak binlerce kayıt alan 2 web sitesini ekleyebilirsiniz.

https://depremyardim.com
https://deprem.io

**Comment by yigitv4rli** [comment]
Yaklasik 2 gundur onemli linklerde mevcut. Fakat anasayfaya da bir fab ekledik. Tesekkurler
