### ISSUE TITLE
Eczaneler [Arapça]

### ISSUE THREAD

**Issue by sadikkuzu** [alpaylan/afetbilgi.com#77]
Ana sayfadaki "Konteyner Eczaneler" butonunun "صيدليات الحاويات" yapılması

![image](https://user-images.githubusercontent.com/23168063/217918736-41460944-8a2a-42cf-910e-f684ec998546.png)

**Comment by oznakn** [comment]
Çok teşekkürler, güncelledik, birazdan yayınlanmış olur.

**Comment by sadikkuzu** [comment]
Teşekkürler hocam ellerinize sağlık
