### ISSUE TITLE
Olmayan URL Adresleri

### ISSUE THREAD

**Issue by coderserdar** [alpaylan/afetbilgi.com#87]
![Screenshot_5](https://user-images.githubusercontent.com/11051271/218028347-08ae30e3-228c-4176-9888-4ca2c6bebae1.png)
Burada bazı konaklama bilgilerinde URL adresi olmadığı halde metinler görünüyor
Bunun bilgisini vermek istedim
İyi çalışmalar

**Comment by alpaylan** [comment]
Bunun olma sebebi renderda mı, yoksa linkler mi kırık?

**Comment by coderserdar** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/11051271/218110113-b040f5e5-3a3c-45d4-b9ba-e86d84399b29.png)
Google Spreadsheet adresindeki csv dosyasında bir URL adresi bulunmuyor İslahiye için mesela
Burada bir null kontrolü yapılsa daha iyi olur diye düşünüyorum

**Comment by oznakn** [comment]
@coderserdar sorun çözülmüş olmalı, kontrol edebilir misiniz?

**Comment by coderserdar** [comment]
Sorun giderilmiş. Elinize sağlık
